name: Download and Chunk File

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: "aPE9oja2l02Ip5RZBroQLYzOrqFCo5EVg3Kjya2U"
  AWS_SECRET_ACCESS_KEY: "AKIATHS5MDWQSTJYISMO"
  S3_BUCKET: yashbucket-0622
  FILE_KEY: ip_addresses.csv
  CHUNK_SIZE: 100  # Specify the chunk size in bytes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Download file from S3 bucket
        run: |
          python -c "import boto3; s3 = boto3.client('s3', region_name='${{ env.AWS_REGION }}'); s3.download_file('${{ env.S3_BUCKET }}', '${{ env.FILE_KEY }}', 'ip_addresses.csv')"


          
